title: Kai Torben Ohlhus
author: Kai Torben Ohlhus
email: k.ohlhus@gmail.com
github: siko1056
description: > # this means to ignore newlines until "baseurl:"
  Some blog about stuff I do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://siko1056.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5

feed:
  excerpt_only: true

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blog"
   link: "/"
# - name: "Resume"
#   link: "/resume"
 - name: "Contact"
   link: "/contact"

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
