title: siko1056.github.io
author: Kai Torben Ohlhus
email: k.ohlhus@gmail.com
github: siko1056
image: /assets/img/kai_ohlhus.jpg
description: >- # this means to ignore newlines until "baseurl:"
  Some blog about my free/libre and open-source software
  projects and public talks (topics: GNU Octave, Linux, etc.).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://siko1056.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blog"
   link: "/"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/siko1056"
 - name: "Contact"
   link: "/contact"

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
