project:
  type: website

website:
  description: "Blog posts from siko1056  "
  site-url: https://siko1056.github.io/
  title: "siko1056"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/siko1056/siko1056.github.io
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



